- name: Deploy nginx sites config
  template: src=mysite.j2 dest="/etc/nginx/sites-enabled/mysite"
  notify: restart nginx
  tags: configuration

- name: Remove default config
  file: path="/etc/nginx/sites-enabled/default" state=absent
  tags: configuration